package com.stormnet.task31.servlet;

public class IndexServletCopy {
    String[] MESSAGE = new String[]{"<strong style=\"color: red\">Введены неверные данные</strong>"};
    String lastName = "value=\"\"";
    String name = "value=\"\"";
    String middleName = "value=\"\"";
    String password = "value=\"\"";
    String age = "value=\"\"";
    String sexMen = "";
    String sexWomen = "";
    String courseJavaSE = "";
    String courseJavaEE = "";
    String coursePython = "";
    String courseHTMLCSS = "";
    String courseJavaScript = "";
    String coursePHPSQL = "";
    String courseTester = "";
    String teacherIvanov = "";
    String teacherPetrov = "";
    String teacherSidorov = "";
    String gradeOne = "";
    String gradeTwo = "";
    String gradeThree = "";
    String gradeFour = "";
    String gradeFive = "";
    String otherCourseJavaSE = "";
    String otherCourseJavaEE = "";
    String otherCoursePython = "";
    String otherCourseHTMLCSS = "";
    String otherCourseJavaScript = "";
    String otherCoursePHPSQL = "";
    String otherCourseTester = "";
    String tv = "";
    String radio = "";
    String inet = "";
    String metro = "";
    String friends = "";
    String other = "";
    String otherText = "value=\"\"";
    String recommendations = "value=\"\"";
}
